title : 'Corvins Blog'
description: 'A personal Blog about Software and Dispair'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
plugins:
  - jekyll-gist
  - jemoji
permalink: /:year/:month/:title.html
